### ISSUE TITLE
Include rescan-scsi-bus.sh in make install

### ISSUE THREAD

**Issue by Malvineous** [hreinecke/sg3_utils#19]
Would it be possible to include `rescan-scsi-bus.sh` in the `make install` process?  Currently the manpage gets installed but the script itself doesn't.

**Comment by hreinecke** [comment]
Oh. Sure. That got missed at the time we've included the rescan-scsi-bus.sh script.

**Comment by doug-gilbert** [comment]
The issue was that some other package (in Debian ?) provided that utility (perhaps one written by Kurt Garloff, the original author). And if that other package was installed first then an attempt to install sg3-utils would fail since it would attempt to overwrite a file belonging to some other package. Not sure if that is still a problem, so I have modified the Makefile.am in the scripts folder to do the install. Lets see what happens. That will appear in my (Subversion) rev 718. I sent Hannes an incemental dump of revs 711 through 717 yesterday. However the main branch of this repository is only synced up to rev 710 (as I write). Hopefully it will catch up shortly.

**Comment by hreinecke** [comment]
repository has been updated to r717.
Doug, can you send the the incremental dump for r718 (and later, if you have them)?

**Comment by hreinecke** [comment]
Has been addressed with r718.
