### ISSUE TITLE
sg_ses command fails when reading overall elements

### ISSUE THREAD

**Issue by vishalm50** [hreinecke/sg3_utils#93]
sg_ses command is failing when reading overall elements for voltage sensor. This issue is seen with multiple enclosure OEMs (DataON, Dell & Supermicro).
This issue is not present in the older releases of sg_ses. We have noticed that sg3_utils-1.47 version does not have this issue.

------------------------------------------------------------------------------------

# lsscsi -g
[0:0:299:0]  enclosu DataON   DNS-2640         0105  -          /dev/sg0

# ./sg_ses --get=disable --index=vs,-1 /dev/sg0
0
0
index: 8,-1-0 not found
Some error occurred, try again with '-v' or '-vv' for more information

[debugdata.zip](https://github.com/hreinecke/sg3_utils/files/11247472/debugdata.zip)

-------------------------------------------------------------------------------------
Capturing below debug data. Please let me know if further information is required.
sg_ses --page=all -HHHH /dev/sg0  > debugdata.hex

**Comment by doug-gilbert** [comment]
Thanks for reporting this and especially for supplying debugdata.hex . It is certainly a bug associated with my attempt to generalize a range of indexes (e.g. 0-5), to include the overall element (e.g. -1-5). And because "-1-5" looks pretty bad, I switched to using ":" as a range separator, so "-1-5" becomes "-1:5". Also I would like "-1:255" to work, even if "16-255" don't exist. As long as there is at least one match then I don't want to treat it as an error. My problem is effectively testing all those variations :-)
An improved version should be over at https://github.com/doug-gilbert/sg3_utils in about 12 hours, after sleep, coffee and more testing.

**Comment by doug-gilbert** [comment]
That should be fixed now. Could you retest using the revision over at my github site and report back.

**Comment by vishalm50** [comment]
Problem is not seen anymore with the latest changes.
